package gateway

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"wktbox/internal/config"
)

var (
	boxIDPattern     = regexp.MustCompile(`^[a-f0-9]{12}$`)
	routeNamePattern = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$`)
)

func Render(routes map[string]config.Route, boxID string) ([]byte, error) {
	if !boxIDPattern.MatchString(boxID) {
		return nil, fmt.Errorf("invalid box ID %q", boxID)
	}
	names := make([]string, 0, len(routes))
	for name, route := range routes {
		if !routeNamePattern.MatchString(name) {
			return nil, fmt.Errorf("invalid gateway route name %q", name)
		}
		if route.Port < 1 || route.Port > 65535 {
			return nil, fmt.Errorf("gateway route %q has invalid port %d", name, route.Port)
		}
		names = append(names, name)
	}
	sort.Strings(names)

	var result strings.Builder
	result.WriteString("# Generated by wktbox. Do not edit.\n")
	result.WriteString("map $http_upgrade $connection_upgrade {\n")
	result.WriteString("    default upgrade;\n")
	result.WriteString("    ''      close;\n")
	result.WriteString("}\n\n")
	result.WriteString("server {\n")
	result.WriteString("    listen 8080 default_server;\n")
	result.WriteString("    server_name _;\n")
	result.WriteString("    return 404;\n")
	result.WriteString("}\n")

	for _, name := range names {
		route := routes[name]
		fmt.Fprintf(&result, "\nserver {\n")
		fmt.Fprintf(&result, "    listen 8080;\n")
		fmt.Fprintf(
			&result,
			"    server_name %s.%s.localhost;\n\n",
			name,
			boxID,
		)
		result.WriteString("    location / {\n")
		fmt.Fprintf(&result, "        proxy_pass http://docker:%d;\n", route.Port)
		result.WriteString("        proxy_http_version 1.1;\n")
		result.WriteString("        proxy_set_header Host $host;\n")
		result.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
		result.WriteString(
			"        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n",
		)
		result.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
		result.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
		result.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		result.WriteString("        proxy_set_header Connection $connection_upgrade;\n")
		result.WriteString("        proxy_read_timeout 3600s;\n")
		result.WriteString("        proxy_send_timeout 3600s;\n")
		result.WriteString("    }\n")
		result.WriteString("}\n")
	}
	return []byte(result.String()), nil
}
